# Generated by Django 4.0.5 on 2022-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d'),
        ),
    ]
